// AUTO-GENERATED by QA Mesh agent
import { Page, Locator } from '@playwright/test';

export class InventoryPage {
  readonly page: Page;
  readonly hamburgerMenu: Locator;
  readonly logoutButton: Locator;

  constructor(page: Page) {
    this.page = page;
    this.hamburgerMenu = page.locator('#react-burger-menu-btn');
    this.logoutButton = page.locator('#logout_sidebar_link');
  }

  async clickHamburgerMenu() {
    await this.hamburgerMenu.click();
  }

  async logout() {
    await this.logoutButton.click();
  }
}
