// AUTO-GENERATED by QA Mesh agent
import { test, expect } from '@playwright/test';
import { LoginPage } from './pages/LoginPage';
import { InventoryPage } from './pages/InventoryPage';

test.describe('dem-2', () => {
  test('Login with valid credentials then logout via hamburger menu', async ({ page }) => {
    const loginPage = new LoginPage(page);
    const inventoryPage = new InventoryPage(page);

    await loginPage.goto();
    await loginPage.login('standard_user', 'secret_sauce');

    await expect(page).toHaveURL(/inventory/);

    await inventoryPage.logout();

    await expect(page).toHaveURL(/login/);
  });
});
