// AUTO-GENERATED by QA Mesh agent
import { test, expect } from '@playwright/test';
import { LoginPage } from './pages/LoginPage';

test.describe('Logout', () => {
  test.skip(({ browserName }) => browserName !== 'chromium', 'Solo se ejecuta en Chrome');

  test('login successfully then logout via hamburger menu', async ({ page }) => {
    const loginPage = new LoginPage(page);

    await loginPage.goto();
    await loginPage.login('standard_user', 'secret_sauce');

    await expect(page).toHaveURL(/inventory/);

    // Click hamburger menu
    await page.locator('#react-burger-menu-btn').click();

    // Wait for menu to be visible
    await page.locator('.bm-menu').waitFor({ state: 'visible' });

    // Click logout button
    await page.locator('#logout_sidebar_link').click();

    // Verify redirect to login page
    await expect(page).toHaveURL(/\//);
    await expect(page.locator('.login_logo')).toBeVisible();
  });
});